#!/bin/bash
# Backup script for Kirby Task Board database
# Run this daily to backup the SQLite database to GitHub

set -e

# Configuration
BACKUP_REPO="https://github.com/bphillipsrver/kirby-taskboard.git"
DB_PATH="/data/tasks.db"  # Path on Render
BACKUP_DIR="/tmp/kirby-backup-$(date +%Y%m%d-%H%M%S)"
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "🗄️ Starting backup process..."
echo "📅 Date: $DATE"

# Create backup directory
mkdir -p "$BACKUP_DIR"
cd "$BACKUP_DIR"

# Clone the backup branch
echo "📥 Cloning backup repository..."
git clone --single-branch --branch backups "$BACKUP_REPO" . 2>/dev/null || {
    echo "Backup branch doesn't exist, creating from main..."
    git clone "$BACKUP_REPO" .
    git checkout -b backups
}

# Export database to SQL
echo "💾 Exporting database..."
if [ -f "$DB_PATH" ]; then
    sqlite3 "$DB_PATH" ".dump" > "backup-${TIMESTAMP}.sql"
    sqlite3 "$DB_PATH" ".backup" "backup-${TIMESTAMP}.db"
    
    # Also export as JSON for readability
    sqlite3 "$DB_PATH" -json "SELECT * FROM tasks" > "tasks-${TIMESTAMP}.json"
    
    echo "✅ Database exported successfully"
else
    echo "❌ Database file not found at $DB_PATH"
    exit 1
fi

# Clean up old backups (keep only last 30 days)
echo "🧹 Cleaning up old backups..."
find . -name "backup-*.sql" -type f -mtime +30 -delete
find . -name "backup-*.db" -type f -mtime +30 -delete
find . -name "tasks-*.json" -type f -mtime +30 -delete

# Commit and push
echo "📤 Committing backup to GitHub..."
git add -A
git commit -m "Daily backup: $DATE

- SQL dump: backup-${TIMESTAMP}.sql
- Binary backup: backup-${TIMESTAMP}.db
- JSON export: tasks-${TIMESTAMP}.json

Auto-generated by backup script" || {
    echo "No changes to commit"
    exit 0
}

git push origin backups

echo "✅ Backup completed successfully!"
echo "📁 Backup location: $BACKUP_REPO (backups branch)"

# Cleanup
rm -rf "$BACKUP_DIR"
